spring.application.name=bodega

spring.datasource.url=jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/bodega?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3&serverTimezone=UTC
spring.datasource.username=L9X8gwnF7TauUFY.root
spring.datasource.password=Cb9k0V7OIhsTcbdp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=e6fdf2e0fa09637479b4f0b67c449f7edb5172c14044ce3288b9317dd671c9f1de54d39a5c31d664f44ba4bf1566d310ec98d7ba8385e15939c23279ee817a7b